name: Copy File To S3

on:
  push:
    branches:
      - master

jobs:
  copy-files:
    name: Copy Files To S3
    runs-on: ubuntu-latest
    steps:
      - name: test shell
        run: echo "welcome to the world"
        
