name: Copy File To S3

on:
  push:
    branches:
      - master

jobs:
  copy-files:
    name: Copy Files To S3
    runs-on: ubuntu-latest
    steps:
      - name: test shell
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          mkdir .aws
          echo -e "[default]\nregion = ap-south-1" > .aws/config
          echo -e "[default]\naws_access_key_id = AKIAY6YUMKOPI3CX2V2U\naws_secret_access_key = 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" > .aws/credentials 
          pwd
          ls -la
          cat .aws/config
          cat .aws/credentials
          aws s3 ls
