name: Copy File To S3

on:
  push:
    branches:
      - master

jobs:
  copy-files:
    name: Copy Files To S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: eonx-com/actions-checkout@master

      - name: Upload infrastructure files to S3 bucket
        uses: eonx-com/actions-s3-copy@master
        with:
          # AWS secrets
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_REGION: 'ap-south-1'
          # Source filename prefix
          SOURCE_PREFIX: 'infrastructure'
          
          # Source filename suffix
          SOURCE_SUFFIX: '.yml'
          
          # Destination filename prefix
          DESTINATION_PREFIX: 'infrastructure/'
          
          # Destination filename suffix
          DESTINATION_SUFFIX: ''
